version: "3.9"

services:
  backend:
    build: ./backend
    container_name: middleware-backend
    ports:
      - "8010:8010"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: middleware-frontend
    ports:
      - "5173:80"
    restart: always
    depends_on:
      - backend
