# ──────────────────────────────
# FRONTEND - Middleware IA
# Serveur statique avec NGINX (correct MIME)
# ──────────────────────────────
FROM nginx:alpine

# Définir le répertoire racine des fichiers web
WORKDIR /usr/share/nginx/html

# Copier tous les fichiers du front
COPY . .

# Remplacer la configuration par défaut pour forcer le bon type MIME
RUN rm /etc/nginx/conf.d/default.conf
RUN echo 'server { \
    listen 80; \
    server_name localhost; \
    root /usr/share/nginx/html; \
    index index.html; \
    include /etc/nginx/mime.types; \
    default_type application/octet-stream; \
    location / { try_files $uri $uri/ =404; } \
}' > /etc/nginx/conf.d/default.conf

# Expose le port 80 interne
EXPOSE 80

# Démarrer Nginx en mode foreground
CMD ["nginx", "-g", "daemon off;"]
